version: '3.8'

services:
  # web:
  #   image: leon-web
  #   build:
  #     context: ./web
  #   volumes:
  #     - ./web:/app
  #     - node_modules:/app/node_modules
  #   ports:
  #     - 8080:8080
  #   # links:
  #   #   - api
  #   networks:
  #     - mobile-wallet-network
  api:
    image: leon-api
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
    restart: always
    env_file:
      - .env.development
      # - .env.production
    depends_on:
      db:
        condition: service_healthy
    # links:
    #   - db
    networks:
      - mobile-wallet-network
  db:
    image: leon-db
    build:
      context: ./db
    restart: always
    environment:
      - POSTGRES_DB=leon-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mobile-wallet-network

volumes:
  node_modules:

networks:
  mobile-wallet-network:
