version: '3.8'

services:
  server:
    build: ./server
    ports:
      - 8080:8080
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      SERVICE_PORT: 8080

  db:
    image: 'postgres:14.2'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./server/db/schema/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./server/db/schema/02-dummy-db.sql:/docker-entrypoint-initdb.d/02-dummy-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 2s

  redis-server:
    image: 'redis:alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    depends_on:
      - redis-server
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379

networks:
  digital-wallet-network:

volumes:
  postgres_digital_wallet:
    name: postgres_digital_wallet
