version: '3.8'

services:
  web:
    image: leon-web
    build:
      context: ./web
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    links:
      - api
  api:
    image: leon-api
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: leon-db
    build:
      context: ./db
    restart: always
    environment:
      - POSTGRES_DB=leon-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
